# All: cpp unity
All: cpp

clean: cleanCppUTest cleanUnity

unity: codeUnity

cpp: codeCppUTest

codeUnity:
	make -i -f MakefileUnity.mk

cleanUnity:
	make -i -f MakefileUnity.mk clean

codeCppUTest: 
	make -i -f MakefileCppUTest.mk

cleanCppUTest:
	make -i -f MakefileCppUTest.mk clean
