OBJ_NAME = a.out

PROJECT_ROOT = ../../../

SRC_FILES =  \
            main.c \
            ../CirculerBuffer.c \

INC_DIRS =  \
            $(PROJECT_ROOT)/include/CirculerBuffer/

$(OBJ_NAME) : 
	gcc -I$(INC_DIRS) $(SRC_FILES)

